pub mod autopilot;
pub mod circuit_breaker;
pub mod gateway;
pub mod hibernation;
pub mod ipc;
pub mod protocol;
pub mod ring_buffer;
pub mod scheduler;
pub mod supervisor;
pub mod telemetry;
pub mod web_dashboard;
pub mod webhooks;

pub use autopilot::AutopilotEngine;
pub use circuit_breaker::{CircuitBreakerInfo, CircuitDecision, CircuitState, CrashCircuitBreaker};
pub use gateway::GatewayServer;
pub use hibernation::HibernationManager;
pub use ipc::{DaemonClient, DaemonServer, DAEMON_PORT};
pub use protocol::{AutoscaleServerStatus, IpcRequest, IpcResponse};
pub use ring_buffer::RingBuffer;
pub use scheduler::{BackupSchedule, BackupScheduleInfo, DaemonScheduler};
pub use supervisor::Supervisor;
pub use telemetry::{generate_prometheus_metrics, init_telemetry_start_time};
pub use web_dashboard::DASHBOARD_HTML;
pub use webhooks::{WebhookDispatcher, WebhookPayload};
