[package]
name = "craft-providers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
craft-core.workspace = true
craft-scripting.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures-util.workspace = true
modalx.workspace = true
indicatif.workspace = true
tracing.workspace = true
thiserror.workspace = true
sha2.workspace = true
hex.workspace = true
zip.workspace = true
tar.workspace = true
flate2.workspace = true
tempfile.workspace = true
zstd = { workspace = true }
