use std::fs;
use std::path::Path;
use colored::Colorize;
use craft_core::Result;
use crate::cli::TemplateCommands;

pub fn handle_template(action: TemplateCommands) -> Result<()> {
    match action {
        TemplateCommands::Plugin { name, platform } => {
            let target_dir = Path::new(&name);
            fs::create_dir_all(target_dir.join("src/main/java/com/example"))?;
            fs::create_dir_all(target_dir.join("src/main/resources"))?;
            fs::create_dir_all(target_dir.join(".vscode"))?;

            // build.gradle.kts
            let gradle_content = r#"plugins {
    `java-library`
}

group = "com.example"
version = "1.0.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}
"#;
            fs::write(target_dir.join("build.gradle.kts"), gradle_content)?;
            fs::write(target_dir.join("settings.gradle.kts"), format!("rootProject.name = \"{}\"\n", name))?;

            // paper-plugin.yml
            let plugin_yml = format!(r#"name: {name}
version: '1.0.0'
main: com.example.{name}Plugin
api-version: '1.21'
author: CraftDeveloper
"#);
            fs::write(target_dir.join("src/main/resources/paper-plugin.yml"), plugin_yml)?;

            // Main class
            let main_java = format!(r#"package com.example;

import org.bukkit.plugin.java.JavaPlugin;

public final class {name}Plugin extends JavaPlugin {{
    @Override
    public void onEnable() {{
        getLogger().info("{name} has been enabled successfully!");
    }}

    @Override
    public void onDisable() {{
        getLogger().info("{name} has been disabled.");
    }}
}}
"#);
            fs::write(target_dir.join(format!("src/main/java/com/example/{}Plugin.java", name)), main_java)?;

            // VSCode launch.json for remote JVM debugging
            let vscode_launch = r#"{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Attach to Minecraft Server",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        }
    ]
}"#;
            fs::write(target_dir.join(".vscode/launch.json"), vscode_launch)?;

            println!("{}", format!("[OK] Scaffolded {} plugin template in '{}'!", platform, name).green().bold());
            println!("Open with VS Code or IntelliJ and run './gradlew build' to build.");
        }
        TemplateCommands::Datapack { name } => {
            let target_dir = Path::new(&name);
            fs::create_dir_all(target_dir.join(format!("data/{}/tags/function", name)))?;
            fs::create_dir_all(target_dir.join(format!("data/{}/function", name)))?;
            fs::create_dir_all(target_dir.join("data/minecraft/tags/function"))?;

            let pack_mcmeta = r#"{
    "pack": {
        "pack_format": 61,
        "description": "Generated by Craft CLI"
    }
}"#;
            fs::write(target_dir.join("pack.mcmeta"), pack_mcmeta)?;

            let load_tag = format!(r#"{{
    "values": [
        "{name}:load"
    ]
}}"#);
            fs::write(target_dir.join("data/minecraft/tags/function/load.json"), load_tag)?;

            let load_mc = format!("tellraw @a [\"\",{{\"text\":\"[{name}] Datapack loaded!\",\"color\":\"green\"}}]\n");
            fs::write(target_dir.join(format!("data/{}/function/load.mcfunction", name)), load_mc)?;

            println!("{}", format!("[OK] Scaffolded Minecraft datapack in '{}'!", name).green().bold());
        }
    }

    Ok(())
}
