[package]
name = "craft-plugins"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
craft-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
tracing.workspace = true
thiserror.workspace = true
zip = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
toml.workspace = true
zstd = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }

